// <auto-generated />
namespace Restaurant.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class imagefield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(imagefield));
        
        string IMigrationMetadata.Id
        {
            get { return "201512261937166_imagefield"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
